### ISSUE TITLE
examine

### ISSUE THREAD

**Issue by mjako18** [KevinLHansen/1sem-projekt-gruppe32#23]
examine skal udvides lidt så den viser hvad der faktisk er i et rum.
Item liste + exit liste

**Comment by SimonHanel** [comment]
Tænker ikke exit liste skal på. Jeg har gjort så der kommer en exit liste når brugeren bare skriver "go" uden noget exitpoint.

**Comment by mjako18** [comment]
det er også fint, men det virker som om det burde være en del af examine.
Item listen skal være der, måske den ikke skal vises i description ellers giver det ikke nogen mening at have examine
