### ISSUE TITLE
Fix inventory begrænsninger

### ISSUE THREAD

**Issue by SimonHanel** [KevinLHansen/1sem-projekt-gruppe32#28]
Der er i øjeblikket et problem med inventory begrænsninger.

Når man samler flere end 3 ting op, vil man stadigvæk samle den 4. ting op, da den forsvinder fra dens current room, men forbliver usynlig i "show inventory".

Derudover, når man sætter en trap eller en item ned, imens man har 4 ting i sit inventory, vil show inventory efterfølgende kun vise den éne af sine items i inventory'et. Resten er usynlige men befinder sig stadigvæk i inventory'et.

**Comment by mjako18** [comment]
Er fixet, bør måske testes igennem igen for at sikre det hele virker
