### ISSUE TITLE
"Start spil"-condition efter Welcome print

### ISSUE THREAD

**Issue by SimonHanel** [KevinLHansen/1sem-projekt-gruppe32#5]
Efter welcome print teksten, kunne vi oprette en Start Spil "knap" eller command for at prompte brugeren til at skrive når spillet skal startes.

**Comment by mjako18** [comment]
Den er tilføjet, men det kan optimeres lidt.
Brug Parser klassen i stedet for en ny Scanner.

**Comment by mjako18** [comment]
opdateret, men skal omtænkes en smule i forhold til GUI
