### ISSUE TITLE
Set Item Location

### ISSUE THREAD

**Issue by SimonHanel** [KevinLHansen/1sem-projekt-gruppe32#6]
"Genstande i rummene" var et punkt på projektoplægget. Vi skal have lavet en setItemLocation metode som spiller sammen med attributterne i Item klassen

**Comment by mjako18** [comment]
se evt. issue #18 for mere information

**Comment by mjako18** [comment]
Der er både en setup trap og en drop item kommando, med tilhørende metoder.
